# -*- coding: utf-8 -*-
"""181245,181350,181352.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nusEfjFnKMOG3_dIquOiuxJqMpCwRjGM
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# %matplotlib inline
# %matplotlib notebook
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive

path="epidemiology.csv"
data=pd.read_csv(path)
print(data.describe())

rows=len(data)

total_case_country={}
total_case_recovered={}
new_case={}
new_recovered_case={}
total_test={}
total_deceased={}
new_tested={}
data.fillna(0.0,inplace=True)

for i in range(rows):
    if data.loc[i,'date'] not in total_case_country:
        total_case_country[data.loc[i,'date']]=data.loc[i,'total_confirmed']
    else:
        total_case_country[data.loc[i,'date']]=total_case_country[data.loc[i,'date']]+data.loc[i,'total_confirmed']
    if data.loc[i,'date'] not in total_case_recovered:
        total_case_recovered[data.loc[i,'date']]=data.loc[i,'total_recovered']
    else:
        total_case_recovered[data.loc[i,'date']]=total_case_recovered[data.loc[i,'date']]+data.loc[i,'total_recovered']
    if data.loc[i,'date'] not in new_case:
        new_case[data.loc[i,'date']]=data.loc[i,'new_confirmed']
    else:
        new_case[data.loc[i,'date']]=new_case[data.loc[i,'date']]+data.loc[i,'new_confirmed']
    if data.loc[i,'date'] not in new_recovered_case:
        new_recovered_case[data.loc[i,'date']]=data.loc[i,'new_recovered']
    else:
      new_recovered_case[data.loc[i,'date']]=data.loc[i,'new_recovered']+new_recovered_case[data.loc[i,'date']]
    if data.loc[i,'date'] not in total_test:
        total_test[data.loc[i,'date']]=data.loc[i,'total_tested']
    else:
        total_test[data.loc[i,'date']]=data.loc[i,'total_tested']+total_test[data.loc[i,'date']]
    if data.loc[i,'date'] not in total_deceased:
        total_deceased[data.loc[i,'date']]=data.loc[i,'total_deceased']
    else:
        total_deceased[data.loc[i,'date']]=data.loc[i,'total_deceased']+total_deceased[data.loc[i,'date']]
    if data.loc[i,'date'] not in new_tested:
        new_tested[data.loc[i,'date']]=data.loc[i,'new_tested']
    else:
        new_tested[data.loc[i,'date']]=data.loc[i,'new_tested']+new_tested[data.loc[i,'date']]

x_raw=(total_case_country.keys())
x=[]
for i in x_raw:
    x.append(pd.to_datetime(i))

y=list(total_case_recovered.values())
x2=list(total_case_recovered.keys())
y2=list(total_case_country.values())
x3=list(new_case.keys())
y3=list(new_case.values())
x4=list(new_recovered_case.keys())
y4=list(new_recovered_case.values())
x5=list(total_test.values())
plt.xlabel('Date')
plt.ylabel('Total Recovered')
plt.plot((x),list(y2),color='Red')
plt.plot((x),(y),color='Blue')
plt.show()

plt.title('New Case Vs New Recoverd')
plt.plot(x,y3,color='Yellow')
plt.plot(x,y4,color='Green')
plt.xlabel('Date')
plt.show()

plt.title('Total Test')
plt.plot(x,x5,color='Blue')
plt.show()

x7=list(new_tested.values())
plt.title('New Case Vs New Tested')
plt.plot(x,y3)
plt.plot(x,x7)
plt.xlabel('Date')
plt.ylabel('Case/Test')
plt.title('New Case Vs New Tested')
plt.show()

plt.plot(x,x7)
plt.title('Per Day Test')
plt.show()

x6=list(total_deceased.values())
plt.title('Total Deceased Vs Total Case')
plt.plot(x,y2)
plt.plot(x,x6)
plt.xlabel('Date')
plt.show()

plt.title('Deceased Case')
plt.bar(x,x6)
plt.xlabel('Date')
plt.ylabel('Deceased Case')
plt.show()

plt.title('Testing Trend')
plt.plot(x,x5)
plt.xlabel('Date')
plt.ylabel('Total Test')
plt.show()

plt.title('Deceased Vs Total Case')
plt.plot(x,y)
plt.plot(x,x6)
plt.show()

"""India Covid Analysis:

"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My Drive/datasets

covid19_df = pd.read_csv("covid_19_india.csv")
individuals_df = pd.read_csv("IndividualDetails.csv")
excel_file = pd.ExcelFile("Indian States Population and Area.xlsx")
indian_states_df = excel_file.parse('Sheet1')

covid19_df.head()

covid19_df.tail()

covid19_df.shape()

covid19_df.isna().sum()

covid19_df_latest = covid19_df[covid19_df['Date']=="25/04/20"]
covid19_df_latest.head()

covid19_df_latest['Confirmed'].sum()

covid19_df_latest = covid19_df_latest.sort_values(by=['Confirmed'], ascending = False)
plt.figure(figsize=(12,8), dpi=80)
plt.bar(covid19_df_latest['State/UnionTerritory'][:5], covid19_df_latest['Confirmed'][:5],
        align='center',color='lightgrey')
plt.ylabel('Number of Confirmed Cases', size = 12)
plt.title('States with maximum confirmed cases', size = 16)
plt.show()

covid19_df_latest['Deaths'].sum()

covid19_df_latest['Deaths/Confirmed Cases'] = (covid19_df_latest['Confirmed']/covid19_df_latest['Deaths']).round(2)
covid19_df_latest['Deaths/Confirmed Cases'] = [np.nan if x == float("inf") else x for x in covid19_df_latest['Deaths/Confirmed Cases']]
covid19_df_latest = covid19_df_latest.sort_values(by=['Deaths/Confirmed Cases'], ascending=True, na_position='last')
covid19_df_latest.iloc[:10]

covid19_df_latest = covid19_df_latest.drop(['Sno','Date','Time','ConfirmedIndianNational','ConfirmedForeignNational'], axis = 1)
covid19_df_latest.shape()

indian_states_df = indian_states_df[['State', 'Aadhaar assigned as of 2019']]
indian_states_df.columns = ['State/UnionTerritory', 'Population']
indian_states_df.head()

covid19_df_latest = pd.merge(covid19_df_latest, indian_states_df, on="State/UnionTerritory")
covid19_df_latest['Cases/10million'] = (covid19_df_latest['Confirmed']/covid19_df_latest['Population'])*10000000
covid19_df_latest.head()

covid19_df_latest.fillna(0, inplace=True)
covid19_df_latest.sort_values(by='Cases/10million', ascending=False)

df = covid19_df_latest[(covid19_df_latest['Confirmed']>=1000) | (covid19_df_latest['Cases/10million']>=200)]
plt.figure(figsize=(12,8), dpi=80)
plt.scatter(covid19_df_latest['Confirmed'], covid19_df_latest['Cases/10million'], alpha=0.5)
plt.xlabel('Number of confirmed Cases', size=12)
plt.ylabel('Number of cases per 10 million people', size=12)
plt.scatter(df['Confirmed'], df['Cases/10million'], color="red")
for i in range(df.shape[0]):
    plt.annotate(df['State/UnionTerritory'].tolist()[i], xy=(df['Confirmed'].tolist()[i], df['Cases/10million'].tolist()[i]),xytext = (df['Confirmed'].tolist()[i]+1.0, df['Cases/10million'].tolist()[i]+12.0), size=11)
plt.tight_layout()    
plt.title('Visualization to display the variation in COVID 19 figures in different Indian states', size=16)
plt.show()

plt.figure(figsize = (12,8))
sns.heatmap(covid19_df_latest.corr(), annot=True)

individuals_grouped_gender = individuals_df.groupby('gender')
individuals_grouped_gender = pd.DataFrame(individuals_grouped_gender.size().reset_index(name = "count"))
individuals_grouped_gender.head()
plt.figure(figsize=(10,6), dpi=80)
barlist = plt.bar(individuals_grouped_gender['gender'], individuals_grouped_gender['count'], align = 'center', color='grey', alpha=0.3)
barlist[1].set_color('r')
plt.ylabel('Count', size=12)
plt.title('Count on the basis of gender', size=16)
plt.show()

individuals_grouped_date = individuals_df.groupby('diagnosed_date')
individuals_grouped_date = pd.DataFrame(individuals_grouped_date.size().reset_index(name = "count"))
individuals_grouped_date[['Day','Month','Year']] = individuals_grouped_date.diagnosed_date.apply(lambda x: pd.Series(str(x).split("/")))
individuals_grouped_date.sort_values(by=['Year','Month','Day'], inplace = True, ascending = True)
individuals_grouped_date.reset_index(inplace = True)
individuals_grouped_date['Cumulative Count'] = individuals_grouped_date['count'].cumsum()
individuals_grouped_date = individuals_grouped_date.drop(['index', 'Day', 'Month', 'Year'], axis = 1)
individuals_grouped_date.head()

individuals_grouped_date.tail()

individuals_grouped_date = individuals_grouped_date.iloc[3:]
individuals_grouped_date.reset_index(inplace = True)
individuals_grouped_date.columns = ['Day Number', 'diagnosed_date', 'count', 'Cumulative Count']
individuals_grouped_date['Day Number'] = individuals_grouped_date['Day Number'] - 2
individuals_grouped_date
plt.figure(figsize=(12,8), dpi=80)
plt.plot(individuals_grouped_date['Day Number'], individuals_grouped_date['Cumulative Count'], color="grey", alpha = 0.5)
plt.xlabel('Number of Days', size = 12)
plt.ylabel('Number of Cases', size = 12)
plt.title('How the case count increased in India', size=16)
plt.show()

